In [1]:
import numpy as np
import pandas as pd

In [9]:
df= pd.read_csv("cat1.csv")

In [10]:
df.dtypes

CustomerID                object
Gender                    object
Married                   object
City                      object
Offer                     object
Phone Service             object
Multiple Lines            object
Internet Service          object
Internet Type             object
Online Security           object
Online Backup             object
Device Protection Plan    object
Premium Tech Support      object
Streaming TV              object
Streaming Movies          object
Streaming Music           object
Unlimited Data            object
Contract                  object
Paperless Billing         object
Payment Method            object
Customer Status            int64
Churn Category            object
dtype: object

In [11]:
df.head()

,CustomerID,Gender,Married,City,Offer,Phone Service,Multiple Lines,Internet Service,Internet Type,Online Security,...,Premium Tech Support,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Customer Status,Churn Category
0,0002-ORFBO,Female,Yes,Frazier Park,None,Yes,No,Yes,Cable,No,...,Yes,Yes,No,No,Yes,One Year,Yes,Credit Card,0,0
1,0004-TLHLJ,Male,No,Costa Mesa,Offer E,Yes,No,Yes,Fiber Optic,No,...,No,No,No,No,Yes,Month-to-Month,Yes,Bank Withdrawal,1,Competitor
2,0011-IGKFF,Male,Yes,Martinez,Offer D,Yes,No,Yes,Fiber Optic,No,...,No,Yes,Yes,No,Yes,Month-to-Month,Yes,Bank Withdrawal,1,Dissatisfaction
3,0013-EXCHZ,Female,Yes,Camarillo,None,Yes,No,Yes,Fiber Optic,No,...,Yes,Yes,No,No,Yes,Month-to-Month,Yes,Credit Card,1,Dissatisfaction
4,0013-MHZWF,Female,No,Midpines,Offer E,Yes,No,Yes,Cable,No,...,Yes,Yes,Yes,Yes,Yes,Month-to-Month,Yes,Credit Card,0,0

In [13]:
df.columns

Index(['CustomerID', 'Gender', 'Married', 'City', 'Offer', 'Phone Service',
       'Multiple Lines', 'Internet Service', 'Internet Type',
       'Online Security', 'Online Backup', 'Device Protection Plan',
       'Premium Tech Support', 'Streaming TV', 'Streaming Movies',
       'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing',
       'Payment Method', 'Customer Status', 'Churn Category'],
      dtype='object')

In [18]:
df.drop(['Churn Category'],axis=1)

,CustomerID,Gender,Married,City,Offer,Phone Service,Multiple Lines,Internet Service,Internet Type,Online Security,...,Device Protection Plan,Premium Tech Support,Streaming TV,Streaming Movies,Streaming Music,Unlimited Data,Contract,Paperless Billing,Payment Method,Customer Status
0,0002-ORFBO,Female,Yes,Frazier Park,None,Yes,No,Yes,Cable,No,...,No,Yes,Yes,No,No,Yes,One Year,Yes,Credit Card,0
1,0004-TLHLJ,Male,No,Costa Mesa,Offer E,Yes,No,Yes,Fiber Optic,No,...,Yes,No,No,No,No,Yes,Month-to-Month,Yes,Bank Withdrawal,1
2,0011-IGKFF,Male,Yes,Martinez,Offer D,Yes,No,Yes,Fiber Optic,No,...,Yes,No,Yes,Yes,No,Yes,Month-to-Month,Yes,Bank Withdrawal,1
3,0013-EXCHZ,Female,Yes,Camarillo,None,Yes,No,Yes,Fiber Optic,No,...,No,Yes,Yes,No,No,Yes,Month-to-Month,Yes,Credit Card,1
4,0013-MHZWF,Female,No,Midpines,Offer E,Yes,No,Yes,Cable,No,...,No,Yes,Yes,Yes,Yes,Yes,Month-to-Month,Yes,Credit Card,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1021,2219-MVUSO,Male,No,Los Angeles,None,Yes,No,Yes,Cable,No,...,No,No,No,No,No,Yes,Month-to-Month,Yes,Credit Card,1
1022,2223-GDSHL,Male,Yes,Fountain Valley,Offer A,Yes,Yes,Yes,Fiber Optic,Yes,...,Yes,Yes,Yes,Yes,Yes,No,Two Year,Yes,Bank Withdrawal,0
1023,2225-ZRGSG,Female,Yes,Piru,Offer A,Yes,Yes,Yes,Fiber Optic,Yes,...,Yes,Yes,No,No,No,Yes,Two Year,No,Bank Withdrawal,1
1024,2226-ICFDO,Female,Yes,Covelo,None,Yes,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,Yes,Yes,Two Year,Yes,Credit Card,0
1025,2227-JRSJX,Female,No,Monterey Park,Offer D,Yes,No,Yes,Fiber Optic,No,...,No,Yes,Yes,Yes,Yes,Yes,Month-to-Month,Yes,Bank Withdrawal,0

# 0 = Stayed +Joined 1= Churened

In [23]:
df['Customer Status'].unique()
#df['Customer Status'].replace(2,0,inplace=True)

array([0, 1], dtype=int64)

# Train Test and Validate data split

In [24]:
from sklearn.model_selection import train_test_split

# Let's say we want to split the data in 80:10:10 for train:valid:test dataset
train_size=0.6

X = df.drop(columns = ['Customer Status']).copy()
y = df['Customer Status']

# In the first step we will split the data in training and remaining dataset
X_train, X_rem, y_train, y_rem = train_test_split(X,y, train_size=0.6)

# Now since we want the valid and test size to be equal (10% each of overall data). 
# we have to define valid_size=0.5 (that is 50% of remaining data)
test_size = 0.5
X_valid, X_test, y_valid, y_test = train_test_split(X_rem,y_rem, test_size=0.5)

print(X_train.shape), print(y_train.shape)
print(X_valid.shape), print(y_valid.shape)
print(X_test.shape), print(y_test.shape)

(615, 21)
(615,)
(205, 21)
(205,)
(206, 21)
(206,)

(None, None)

# X_train ,y_train  X_valid y_valid   X_test y_test

# Random Forest